-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchased_amount) AS Amount_spent
FROM
    customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id, purchased_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchased_amount > (SELECT 
            AVG(purchased_amount)
        FROM
            customer);
            
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    category,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM
    customer
GROUP BY item_purchased , category
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type, AVG(purchased_amount) AS avg_spent
FROM
    customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard' , 'Express');

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status AS subscriber,
    COUNT(customer_id) AS total_customer,
    ROUND(AVG(purchased_amount),2) AS avg_spent,
    SUM(purchased_amount) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY avg_spent DESC, total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'YES' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
SELECT customer_segment, COUNT(*) AS No_of_customers FROM
(SELECT 
    customer_id, previous_purchases, 
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM 
    customer) AS segmented
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
SELECT *
FROM
(SELECT 
	item_purchased, category, 
	COUNT(customer_id) AS quantity, 
	ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rn 
FROM 
    customer
GROUP BY item_purchased, category) AS ranked
WHERE rn<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    COUNT(customer_id) AS repeat_buyers, subscription_status
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchased_amount) AS revenue,
    CONCAT(ROUND((100 * SUM(purchased_amount)) / (SELECT 
                            SUM(purchased_amount)
                        FROM
                            customer)),
            '%') AS revenue_percentage
FROM
    customer
GROUP BY age_group;
